'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Data.EntityClient
Imports System.ComponentModel
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization

<Assembly:System.Data.Objects.DataClasses.EdmSchemaAttribute()>
Namespace StoredProcedures.Models

#Region "Contexts"
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public Partial Class StoredProcedureEntities
        Inherits System.Data.Objects.ObjectContext

#Region "Constructors"
        ''' <summary>
        ''' Initializes a new StoredProcedureEntities object using the connection string found in the 'StoredProcedureEntities' section of the application configuration file.
        ''' </summary>
        Public Sub New()
            MyBase.New("name=StoredProcedureEntities", "StoredProcedureEntities")
            Me.ContextOptions.LazyLoadingEnabled = True
            Me.OnContextCreated()
        End Sub

        ''' <summary>
        ''' Initialize a new StoredProcedureEntities object.
        ''' </summary>
        Public Sub New(ByVal connectionString As String)
            MyBase.New(connectionString, "StoredProcedureEntities")
            Me.ContextOptions.LazyLoadingEnabled = True
            Me.OnContextCreated()
        End Sub

        ''' <summary>
        ''' Initialize a new StoredProcedureEntities object.
        ''' </summary>
        Public Sub New(ByVal connection As System.Data.EntityClient.EntityConnection)
            MyBase.New(connection, "StoredProcedureEntities")
            Me.ContextOptions.LazyLoadingEnabled = True
            Me.OnContextCreated()
        End Sub

#End Region
#Region "Partial Methods"
        Partial Private Sub OnContextCreated()
        End Sub

#End Region
#Region "ObjectSet Properties"
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property SupportTeams As ObjectSet(Of StoredProcedures.Models.SupportTeam)
            Get
                If(Me._SupportTeams Is Nothing) Then
                    Me._SupportTeams = Me.CreateObjectSet(Of StoredProcedures.Models.SupportTeam)("SupportTeams")
                End If

                Return Me._SupportTeams
            End Get
        End Property

        Private _SupportTeams As System.Data.Objects.ObjectSet(Of StoredProcedures.Models.SupportTeam)

#End Region
#Region "AddTo Methods"
        ''' <summary>
        ''' Deprecated Method for adding a new object to the SupportTeams EntitySet. Consider using the .Add method of the associated ObjectSet&lt; T&gt;  property instead.
        ''' </summary>
        Public Sub AddToSupportTeams(ByVal supportTeam As StoredProcedures.Models.SupportTeam)
            Me.AddObject("SupportTeams", supportTeam)
        End Sub

#End Region
#Region "Function Imports"
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public Function SelectSupportTeam() As ObjectResult(Of StoredProcedures.Models.SelectSupportTeam_Result)
            Return Me.ExecuteFunction(Of StoredProcedures.Models.SelectSupportTeam_Result)("SelectSupportTeam")
        End Function

        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        ''' <param name="id">No Metadata Documentation available.</param>
        Public Function DeleteSupportEngineer(ByVal id As System.Nullable(Of Global.System.Int32)) As ObjectResult(Of System.Nullable(Of Global.System.Int32))
            Dim idParameter As System.Data.Objects.ObjectParameter
            If id.HasValue Then
                idParameter = New System.Data.Objects.ObjectParameter("Id", id)
            Else
                idParameter = New System.Data.Objects.ObjectParameter("Id", GetType(Global.System.Int32))
            End If

            Return Me.ExecuteFunction(Of System.Nullable(Of Global.System.Int32))("DeleteSupportEngineer", idParameter)
        End Function

        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        ''' <param name="name">No Metadata Documentation available.</param>
        Public Function InsertSupportEngineer(ByVal name As Global.System.[String]) As ObjectResult(Of System.Nullable(Of Global.System.[Decimal]))
            Dim nameParameter As System.Data.Objects.ObjectParameter
            If Not Equals(name, Nothing) Then
                nameParameter = New System.Data.Objects.ObjectParameter("name", name)
            Else
                nameParameter = New System.Data.Objects.ObjectParameter("name", GetType(Global.System.[String]))
            End If

            Return Me.ExecuteFunction(Of System.Nullable(Of Global.System.[Decimal]))("InsertSupportEngineer", nameParameter)
        End Function
#End Region
    End Class

#End Region
#Region "Entities"
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="StoredProcedureModel", Name:="SupportTeam")>
    <System.SerializableAttribute()>
    <System.Runtime.Serialization.DataContractAttribute(IsReference:=True)>
    Public Partial Class SupportTeam
        Inherits System.Data.Objects.DataClasses.EntityObject

#Region "Factory Method"
        ''' <summary>
        ''' Create a new SupportTeam object.
        ''' </summary>
        ''' <param name="id">Initial value of the Id property.</param>
        ''' <param name="name">Initial value of the Name property.</param>
        Public Shared Function CreateSupportTeam(ByVal id As Global.System.Int32, ByVal name As Global.System.[String]) As SupportTeam
            Dim supportTeam As StoredProcedures.Models.SupportTeam = New StoredProcedures.Models.SupportTeam()
            supportTeam.Id = id
            supportTeam.Name = name
            Return supportTeam
        End Function

#End Region
#Region "Primitive Properties"
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False)>
        <System.Runtime.Serialization.DataMemberAttribute()>
        Public Property Id As Global.System.Int32
            Get
                Return Me._Id
            End Get

            Set(ByVal value As Global.System.Int32)
                If Me._Id <> value Then
                    Me.OnIdChanging(value)
                    Me.ReportPropertyChanging("Id")
                    Me._Id = System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                    Me.ReportPropertyChanged("Id")
                    Me.OnIdChanged()
                End If
            End Set
        End Property

        Private _Id As Global.System.Int32

        Partial Private Sub OnIdChanging(ByVal value As Global.System.Int32)
        End Sub

        Partial Private Sub OnIdChanged()
        End Sub

        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=False)>
        <System.Runtime.Serialization.DataMemberAttribute()>
        Public Property Name As Global.System.[String]
            Get
                Return Me._Name
            End Get

            Set(ByVal value As Global.System.[String])
                Me.OnNameChanging(value)
                Me.ReportPropertyChanging("Name")
                Me._Name = System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, False)
                Me.ReportPropertyChanged("Name")
                Me.OnNameChanged()
            End Set
        End Property

        Private _Name As Global.System.[String]

        Partial Private Sub OnNameChanging(ByVal value As Global.System.[String])
        End Sub

        Partial Private Sub OnNameChanged()
        End Sub

        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
        <System.Runtime.Serialization.DataMemberAttribute()>
        Public Property ChangeDate As Nullable(Of Global.System.DateTime)
            Get
                Return Me._ChangeDate
            End Get

            Set(ByVal value As Nullable(Of Global.System.DateTime))
                Me.OnChangeDateChanging(value)
                Me.ReportPropertyChanging("ChangeDate")
                Me._ChangeDate = System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("ChangeDate")
                Me.OnChangeDateChanged()
            End Set
        End Property

        Private _ChangeDate As System.Nullable(Of Global.System.DateTime)

        Partial Private Sub OnChangeDateChanging(ByVal value As System.Nullable(Of Global.System.DateTime))
        End Sub

        Partial Private Sub OnChangeDateChanged()
        End Sub
#End Region
    End Class

#End Region
#Region "ComplexTypes"
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <System.Data.Objects.DataClasses.EdmComplexTypeAttribute(NamespaceName:="StoredProcedureModel", Name:="SelectSupportTeam_Result")>
    <System.Runtime.Serialization.DataContractAttribute(IsReference:=True)>
    <System.SerializableAttribute()>
    Public Partial Class SelectSupportTeam_Result
        Inherits System.Data.Objects.DataClasses.ComplexObject

#Region "Factory Method"
        ''' <summary>
        ''' Create a new SelectSupportTeam_Result object.
        ''' </summary>
        ''' <param name="id">Initial value of the Id property.</param>
        ''' <param name="name">Initial value of the Name property.</param>
        Public Shared Function CreateSelectSupportTeam_Result(ByVal id As Global.System.Int32, ByVal name As Global.System.[String]) As SelectSupportTeam_Result
            Dim selectSupportTeam_Result As StoredProcedures.Models.SelectSupportTeam_Result = New StoredProcedures.Models.SelectSupportTeam_Result()
            selectSupportTeam_Result.Id = id
            selectSupportTeam_Result.Name = name
            Return selectSupportTeam_Result
        End Function

#End Region
#Region "Primitive Properties"
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=False)>
        <System.Runtime.Serialization.DataMemberAttribute()>
        Public Property Id As Global.System.Int32
            Get
                Return Me._Id
            End Get

            Set(ByVal value As Global.System.Int32)
                Me.OnIdChanging(value)
                Me.ReportPropertyChanging("Id")
                Me._Id = System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("Id")
                Me.OnIdChanged()
            End Set
        End Property

        Private _Id As Global.System.Int32

        Partial Private Sub OnIdChanging(ByVal value As Global.System.Int32)
        End Sub

        Partial Private Sub OnIdChanged()
        End Sub

        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=False)>
        <System.Runtime.Serialization.DataMemberAttribute()>
        Public Property Name As Global.System.[String]
            Get
                Return Me._Name
            End Get

            Set(ByVal value As Global.System.[String])
                Me.OnNameChanging(value)
                Me.ReportPropertyChanging("Name")
                Me._Name = System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, False)
                Me.ReportPropertyChanged("Name")
                Me.OnNameChanged()
            End Set
        End Property

        Private _Name As Global.System.[String]

        Partial Private Sub OnNameChanging(ByVal value As Global.System.[String])
        End Sub

        Partial Private Sub OnNameChanged()
        End Sub
#End Region
    End Class
#End Region
End Namespace
